### ISSUE TITLE
Installation: calib folder doesn't get copied properly

### ISSUE THREAD

**Issue by steveschulze** [jkrogager/PyNOT#11]
Hi JK,

When I install your pipeline with `python setup.py install` not all files from the directory `calib` get copied.

Cheers,

Steve

**Comment by jkrogager** [comment]
Should be fixed by latest merge #12. Otherwise let me know.
Note that the pixeltables in the calib folder are mere cached copies of recent reductions and should therefore not be copied to individual users as they are supposed to generate them themselves.
