### ISSUE TITLE
Response function issue for standard star

### ISSUE THREAD

**Issue by Shivangi1010** [jkrogager/PyNOT#21]
Hi,
I am not able to flux calibrate the objects due to response function issue.
such as:

[WARNING] - No reference data found for target: BD+332642
[WARNING] - The response function cannot be calculated for this target

-----------------------------------------------------------------------------------------------------------
however, I have seen the std folder under pynot

**Comment by jkrogager** [comment]
Could you please add a bit more context to this? I assume you have observed the star BD+332642. Is this the OBJECT name in the FITS header? Could also be "SP1550+330", either name should work.

And the file bd332642.dat exists in the calib/std folder?

**Comment by Shivangi1010** [comment]
Yes, somehow, the flux calibration task cannot be performed since it cannot find the response function for the mentioned standard star.

And the file bd332642.dat exists in the calib/std folder?  ---yes, it is there
I am getting this error:

          - Running task: Response function
[WARNING] - No reference data found for target: BD+332642
[WARNING] - The response function cannot be calculated for this target

          - Pipeline setup ended successfully.
            Consult the overview log: pynot_30Mar2024-00h00m05.log


          - Loaded OB database: dataset.obd
          - Updating OB database

          - Skipping OB: spectra/QSO1644+263/al-gr4_slit1.8/ob1  (status=DONE)
          - Change OB status to blank in the .obd file if you want to redo the reduction
          - or run the pipeline with the '--science' option to force re-reduction of all OBs

          - Skipping OB: spectra/QSO1644+263/al-gr4_slit1.8/ob2  (status=DONE)
          - Change OB status to blank in the .obd file if you want to redo the reduction
          - or run the pipeline with the '--science' option to force re-reduction of all OBs

Shall I send you the logfile and dataset.pfc file?
I have installed PyNOT using pip.

**Comment by Shivangi1010** [comment]
Is it because response task is not working?
I have tried to type this in the terminal: pynot response 
Traceback (most recent call last):
  File "/home/shivangi/anaconda3/bin/pynot", line 33, in <module>
    sys.exit(load_entry_point('PyNOT-redux==1.3.3', 'console_scripts', 'pynot')())
  File "/home/shivangi/anaconda3/lib/python3.8/site-packages/pynot/main.py", line 675, in main
    from pynot.response_gui import ResponseGUI
  File "/home/shivangi/anaconda3/lib/python3.8/site-packages/pynot/response_gui.py", line 26, in <module>
    from pynot import response
  File "/home/shivangi/anaconda3/lib/python3.8/site-packages/pynot/response.py", line 26, in <module>
    from pynot.data import organizer
  File "/home/shivangi/anaconda3/lib/python3.8/site-packages/pynot/data/organizer.py", line 14, in <module>
    from pynot.response import lookup_std_star
ImportError: cannot import name 'lookup_std_star' from partially initialized module 'pynot.response' (most likely due to a circular import) (/home/shivangi/anaconda3/lib/python3.8/site-packages/pynot/response.py)

**Comment by Shivangi1010** [comment]
Hi,
Please let me know how to get a 1D spectrum of the wavelength-calibrated
file instead of a fits table.
In the spectra folder that is generated, we have a FLUX1D** file that is a
table, now, since I am not able to do flux calibration, I was thinking of
using IRAF for it.
I need a 1D spectrum instead of a table (to run Sens, standard tasks in
IRAF). However, I dont seem to find anything of this sort.
Thank you!
Shivangi Pandey.

**Comment by jkrogager** [comment]
Hi again, could you please attach the .pfc file?

Regarding the 1D spectrum, you'll have to convert it yourself to the IRAF format in that case.

**Comment by Shivangi1010** [comment]
Hi,
I am using only those files which are having configuration, such as Grism4,
slit 1.8 arcsec.

Thank you!
Shivangi Pandey.
