### ISSUE TITLE
Reducing multiple observations in series: re-cycling previously created sens function

### ISSUE THREAD

**Issue by steveschulze** [jkrogager/PyNOT#5]
Hi JK,

If you reduce multiple objects in series, PyNOT re-creates the sensitivity function every time. Could you add an option where PyNOT uses a previously created sens function?

**Comment by jkrogager** [comment]
This should be the default behaviour. It is handled by the option "force" under "response"... If force = True, then the code will generate a new response function for each target. If False, then the code should use the one already generated. I'll double check that it has been implemented correctly.

**Comment by jkrogager** [comment]
This should be updated in the new revamped reduction flow as of version 1.0. Documentation still needs to be updated, sorry, I have been short on time.
