### ISSUE TITLE
Reducing multiple observations in series: wavelength calibration

### ISSUE THREAD

**Issue by steveschulze** [jkrogager/PyNOT#6]
Hi JK,

PyNOT does the wavelength calibration only ones even if you reduce the multiple objects in series. This can cause shifts in the wavelength calibration if the telescope flexure is very different between observations. It would be better if PyNOT chooses for each observation an arc spectrum that is closest in RA and DEC and time to a science observation. I.e., if you reduce multiple objects in series, you would always have to redo the wavelength calibration.

**Comment by jkrogager** [comment]
Hey, thanks for the note. This is indeed how the code works. The code automatically selects the arc frame that matches the slit, grism and observing time of the science exposure. The user can then either re-identify the lines every time (which is a bit tedious) or let PyNOT identify the lines automatically in each new arc exposure. The default is to have the user identify lines once and then store these in cache so the code can re-use them as initial guesses for the following automated fit of arc-line centroids.
